# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet delete-installation start yaml
---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information
  optional: true
- name: automation_repo
  optional: true

params:
  ENV_FILE: env.yml
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  om_username:
  om_password:

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    apt-get update
    apt-get install -y jq

    cat state_dir/"${state_file}" | jq -r .ops_manager_dns | xargs -I# sed -i.bak  's/target:.*$/target: #/g' automation_repo/"${ENV_FILE}"
    echo "username: ${om_username}" >> automation_repo/"${ENV_FILE}"
    echo "password: ${om_password}" >> automation_repo/"${ENV_FILE}"

    om --env automation_repo/"${ENV_FILE}" delete-installation --force
# code_snippet delete-installation end
