---
platform: linux

inputs:
- name: automation_repo
- name: state_dir

params:

  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  env_file:

  # - Required
  # - Filepath of the authorization config YAML
  # - The path is relative to root of the `env` input
  auth_file:

  state_file:

  opsman_admin_user:

  opsman_admin_password:

  opsman_decryption_passphrase:

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    apt-get update
    apt-get install -y jq
    apt-get install -y unzip
    apt-get install -y wget

    #wget https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_linux_amd64.zip
    #unzip terraform_0.12.0_linux_amd64.zip
    #mv terraform /usr/local/bin/
    #terraform --version

    pwd
    ls -R .

    #terraform output -state=state_dir/"${state_file}"  -json | jq -r .ops_manager_dns.value | xargs -I# sed -i.bak  's/target:.*$/target: #/g' automation_repo/"${env_file}"
    cat state_dir/"${state_file}" | jq -r .ops_manager_dns.value | xargs -I# sed -i.bak  's/target:.*$/target: #/g' automation_repo/"${env_file}"

    echo "username: $opsman_admin_user" >> automation_repo/"${auth_file}"
    echo "password: $opsman_admin_password" >> automation_repo/"${auth_file}"
    echo "decryption-passphrase: $opsman_decryption_passphrase" >> automation_repo/"${auth_file}"

    om --env automation_repo/"${env_file}" configure-authentication --config automation_repo/"${auth_file}"
