---
platform: linux

inputs:
- name: env         # directory that contains the env file with target OpsMan Information
- name: config      # directory that contains the auth configuration

params:

  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  env_file: env.yml

  # - Required
  # - Filepath of the authorization config YAML
  # - The path is relative to root of the `config` input
  auth_file: auth.yml

  opsman_admin_user:

  opsman_admin_password:

  opsman_decryption_passphrase:

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    terraform output -state=sandbox/terraform.tfstate -json | jq -r .ops_manager_dns.value | xargs -I_ sed -i '' 's/target:.*$/target: _/g' env/"${env_file}"

    echo "username: $opsman_admin_user" >> env/"${auth_file}"
    echo "password: $opsman_admin_password" >> env/"${auth_file}"
    echo "decryption-passphrase: $opsman_decryption_passphrase" >> env/"${auth_file}"

    om --env env/"${env_file}" configure-authentication --config env/"${auth_file}"
