---
platform: linux

params:

  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  env_file:

  # - Required
  # - Filepath of the authorization config YAML
  # - The path is relative to root of the `env` input
  auth_file:

  opsman_admin_user:

  opsman_admin_password:

  opsman_decryption_passphrase:

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -eux

    terraform output -state=sandbox/terraform.tfstate -json | jq -r .ops_manager_dns.value | xargs -I_ sed -i '' 's/target:.*$/target: _/g' "${env_file}"

    echo "username: $opsman_admin_user" >> "${auth_file}"
    echo "password: $opsman_admin_password" >> "${auth_file}"
    echo "decryption-passphrase: $opsman_decryption_passphrase" >> "${auth_file}"

    om --env "${env_file}" configure-authentication --config "${auth_file}"
